version: 2.1
orbs:
  python: circleci/python@2.1.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install pylint
      - run: pylint digsec/*.py --disable=fixme
      - run: pip install -e .
      - run: bash scripts/validate_second_level_domain.sh metebalci.com A /tmp 8.8.8.8
