version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install -e .
      - run: ./test.sh
      - run: pip install pylint
      - run: pylint digsec/*.py
