version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install pylint
      - run: pip install -e .
      - run: pylint digsec/*.py --disable=fixme --disable=consider-using-f-string
      - run: bash scripts/test.sh
