version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install -e .
      - run: scripts/validate.py . DNSKEY
      - run: scripts/validate.py com DNSKEY
      - run: scripts/validate.py metebalci.com DNSKEY
      - run: scripts/validate.py metebalci.com A

  pylint:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install pylint
      - run: pylint digsec/*.py --disable=fixme --disable=consider-using-f-string

workflows:
  build_and_pylint:
    jobs:
      - build
      - pylint
