version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: pip install -e .
      - run: scripts/validate.py . DNSKEY /tmp
      - run: scripts/validate.py com DNSKEY /tmp
      - run: scripts/validate.py metebalci.com DNSKEY /tmp
      - run: scripts/validate.py metebalci.com A /tmp
      - run: pip install pylint
      - run: pylint digsec/*.py
